### ISSUE TITLE
Implement cascade deletion instead of adhoc code

### ISSUE THREAD

**Issue by pchtsp** [baobabsoluciones/corn#15]
see https://docs.sqlalchemy.org/en/14/orm/cascades.html#delete
this implies deleting the records instead of disabling them, of course. But I like it because it's "automatic" and "standard".

Instead of doing this:

https://github.com/baobabsoluciones/corn/blob/d94a6fb29cb9670734550d076c87909d6bb4071d/cornflow/endpoints/meta_resource.py#L92-L99

**Comment by ggsdc** [comment]
I know that we can delete on cascade, postgres and sql alchemy allow it, but I do not think that we should let the user permanently delete, just disable or set the information for deletion and have an automatic process that deletes that information periodically once a set amount of time has passed

**Comment by pchtsp** [comment]
ok, I close this for now since it's not really urgent.
